version: 2.1

jobs:
  task-manager-front:
    docker:
      - image: cimg/node:20.0

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run tests
          command: npm test -- --watchAll=false

      - run:
          name: Build
          command: npm run build

workflows:
  version: 2
  task-manager-front:
    jobs:
      - task-manager-front
